### ISSUE TITLE
SetColumnsWidth (or SetRowsHeight) vs Frozen

### ISSUE THREAD

**Issue by LamerDrv** [unvell/ReoGrid#313] opened 2020-03-01 08:06 UTC
Hi. When grid has frozen rows or frozen columns then SetColumnsWidth or SetRowsHeight scrolls grid to start position despite the focused cell.

This behavior can be seen in demo project.
1. Start "ReoGrid Demo"
2. Go to "Top" subsection in "Freeze to Edges" section (in tree on left side)
3. scroll grid down and focus cell (for example focus cell "G60")
4. change width any column or height any row
5. grid auto-scroll to start and current cell is out of visible area (but scroll bars position stay corectly)

**Expected behavior**
Current cell stay in visible area

may be same as https://github.com/unvell/ReoGrid/issues/172

**Comment by LamerDrv** [comment] 2020-03-01 08:31
I had tried to track down the issue. And I had come to this fragment inside ViewControl.cs:
```
85: if (this.IsFrozen)
86: {
87:   this.FreezeToCell(this.FreezePos, this.FreezeArea);
88: }
```
I had tried comment out line 87 (just to see what will happen) - and get expected behavior.
I understand that solution can't be so easy :)))) (most certainly removing this string will lead to negative consequences). But I hope this info helps.

**Comment by jingwood** [comment] 2020-03-06 03:34
duplicate of #151

**Closed** 2020-07-07 02:50 UTC
Labels: bug, resolved
