### ISSUE TITLE
Date format problem in 2.1.0.0

### ISSUE THREAD

**Issue by Hoannd2** [unvell/ReoGrid#203] opened 2018-11-30 18:28 UTC
I downloaded newest version (2.1.0.0 package), and i tried ReoGridEditor, i cannot set cell format for datetime, it always display as MM/dd/yyyy

**Comment by TimDoesCode** [comment] 2019-02-12 15:40
I have encountered the same problem, except it displays dd.MM.yyyy for me. 

I guess it defaults to the default format set by the OS culture?

**Comment by ks1974in** [comment] 2019-03-20 19:11
The issue is in core/DataFormat.cs. The value passed as format string is always ignored. You can fix this as below

public class DateTimeDataFormatter : IDataFormatter{

public string FormatCell(Cell cell)
		{
/*************Other code*********************/
Line 974
/*Actual Code Will always ignore dargs.Format because pattern is NEVER null or empty [ It is a default value]*/
					String pattern = System.Threading.Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern;

				if (cell.DataFormatArgs != null && cell.DataFormatArgs is DateTimeFormatArgs)
				{
					DateTimeFormatArgs dargs = (DateTimeFormatArgs)cell.DataFormatArgs;
                    //BUG -FIX APPLIED 
                    if(dargs.Format!=null  || dargs.Format!=String.Empty)
					//if (pattern == null || pattern == String.Empty)
					{
						pattern = dargs.Format;
					}
//The code should be as follows

string pattern = System.Threading.Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern;

				if (cell.DataFormatArgs != null && cell.DataFormatArgs is DateTimeFormatArgs)
				{
					DateTimeFormatArgs dargs = (DateTimeFormatArgs)cell.DataFormatArgs;
                    //BUG -FIX APPLIED 
                    if(dargs.Format!=null  || dargs.Format!=String.Empty)
			{
						pattern = dargs.Format;
			}

	}

**Comment by ks1974in** [comment] 2019-03-21 04:07
The above doesnt work in the WPF version of ReoGrid 2.1.0. I could not figure out why it works in the Winforms version and not in the wpf verion

**Comment by bltgpa** [comment] 2019-03-29 15:32
Hi,
Nice fix. I used the custom DataFormater to integrate it in the Nuget Package.
Do you think that fix will be integrate soon in a new version ?

Thanks for your great job with ReoGrid

**Comment by ks1974in** [comment] 2019-03-30 00:07
Happy to be of assistance. Unfortunately, I couldn't get this to work in
WPF version.  I am using the project in the form of source code, and not
from nuget, because I don't know when the fix will be integrated.
Thanks

**Comment by lamazze** [comment] 2020-02-24 11:18
Hello,
Any plan and/or release date on a fix ?
I could use the source directly but I've rather stick with the Nuget package.
For some reason the custom DataFormater isn't working for me. Or more precisely, when I add a custom formatter, it tries to apply it to all my cells even those who don't have the CellDataFormatFlag.Custom flag.
Thank you

**Comment by jingwood** [comment] 2020-02-24 16:01
I will apply this fix and publish a nuget package within recent days. Thanks @ks1974in for the code.

**Comment by lamazze** [comment] 2020-02-24 18:56
Thank you very much

**Comment by jingwood** [comment] 2020-02-26 16:30
Now the nuget package 2.2.0 has been published.

**Closed** 2021-04-03 16:40 UTC
Labels: bug, resolved
